name: CI

on:
  push:
    branches: ["production"]
  pull_request:

jobs:
  php-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ["8.1", "8.2", "8.3"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer
          coverage: none
      - name: Install dependencies
        run: |
          composer install --no-interaction --prefer-dist
        working-directory: ./ec-nordheide-wp-mitarbeiter
      - name: Syntax check
        run: |
          find . -type f -name "*.php" -not -path "./vendor/*" -print0 | xargs -0 -n1 -P4 php -l
        working-directory: ./ec-nordheide-wp-mitarbeiter
      - name: WordPress Coding Standards
        run: |
          vendor/bin/phpcs -p --standard=ruleset.xml .
        working-directory: ./ec-nordheide-wp-mitarbeiter
